### ISSUE TITLE
AU title mentions PKP PLN

### ISSUE THREAD

**Issue by mjordan** [ubermichael/westvault-vagrant#3]
In the LOCKSS subscription manager, AUs generated by OwnCloud have "PKP PLN" in their title. See attached screencap for an example.

![subscription_manager](https://user-images.githubusercontent.com/403918/32346074-5979b3ca-bfc9-11e7-945b-2cf9577b845d.png)

**Comment by ubermichael** [comment]
I think this is a problem in either the LOCKSS Plugin or the staging server. I'll need to figure that out later tonight.
